name: run-struct

on:
  workflow_dispatch:

jobs:
  generate:
    uses: httpdss/struct/.github/workflows/struct-generate.yaml@main
    with:
      struct_file: 'file://.struct.yaml'
      output_dir: '.'
      pr_base: 'master'
    secrets:
      token: ${{ secrets.STRUCT_RUN_TOKEN }}
